# Generated by Django 3.2.7 on 2022-02-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isSmoke', models.BooleanField()),
                ('isDiabetes', models.BooleanField()),
                ('isFever', models.BooleanField()),
            ],
        ),
    ]
