# Generated by Django 3.2.7 on 2022-02-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhealth',
            name='diseaseImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='userhealth',
            name='isDiabetes',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='userhealth',
            name='isFever',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='userhealth',
            name='isSmoke',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
